In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import contextily as cx
import plotly.express as px
import folium
from folium import plugins
from folium.plugins import HeatMap

In [3]:
df = pd.read_csv('../../Grupo5_Analisis/Data/population-cleaned.csv')
df.head()

,Name,ASCII Name,Alternate Names,Country Code,Country name EN,Population,Timezone,LABEL EN,Latitude,Longitude
0,Pizhanka,Pizhanka,"Pizhanka,Pizjanka,Пижанка",RU,Russian Federation,3900.0,Europe/Kirov,Russian Federation,57.46042,48.54200
1,Pitelino,Pitelino,"Petelino,Pitelino,Пителино",RU,Russian Federation,2355.0,Europe/Moscow,Russian Federation,54.57768,41.81448
2,Petro-Slavyanka,Petro-Slavyanka,"Petro-Slav'anka,Petro-Slavjanka,Petro-Slavyank...",RU,Russian Federation,1308.0,Europe/Moscow,Russian Federation,59.80222,30.50694
3,Palkino,Palkino,"Palkino,Палкино,Պալկինո",RU,Russian Federation,3112.0,Europe/Moscow,Russian Federation,57.54089,28.01257
4,Orlovka,Orlovka,"Orlovka,Орловка",RU,Russian Federation,3236.0,Europe/Moscow,Russian Federation,44.69139,44.17444

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140632 entries, 0 to 140631
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Name             140632 non-null  object
 1   ASCII Name       140631 non-null  object
 2   Alternate Names  116241 non-null  object
 3   Country Code     140587 non-null  object
 4   Country name EN  140464 non-null  object
 5   Population       140632 non-null  float64
 6   Timezone         140632 non-null  object
 7   LABEL EN         140464 non-null  object
 8   Latitude         140632 non-null  float64
 9   Longitude        140632 non-null  float64
dtypes: float64(3), object(7)
memory usage: 10.7+ MB